### ISSUE TITLE
Make /logs configurable

### ISSUE THREAD

**Issue by bahlo** [axiomhq/axiom-cloudfront-lambda#8]
You can configure the subdirectory for CloudFront logs, so we should make it configurable in the stack(s) too

**Comment by a-khaledf** [comment]
we don't use the subdirectory of the CloudFront logs in the stack or handler.py

**Comment by bahlo** [comment]
But for the bucket subscription we set a prefix, don't we?

**Comment by a-khaledf** [comment]
we don't have a subscription filter right now, but I will add it as input and pass it to the subscription filter
